config/routes.rb
DansTheMan::Application.routes.draw do
  devise_for :users
  root to: "dashboard#index"

  resources :guests
  resources :addresses
  resources :add_guests

  match "add_guests/guest",            to: "add_guests#create_guest", via: "post"
  match "add_guests/address",          to: "add_guests#create_address", via: "post"
  match "add_guests/additional_guest", to: "add_guests#create_additional_guest", via: "post"

  match "dashboard", to: "dashboard#index", via: "get"

end

app/models/address.rb
class Address < ActiveRecord::Base
  validates_presence_of :street_address
end

app/models/guest.rb
class Guest < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :first_name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :guests
end

app/controllers/add_guests_controller.rb
class AddGuestsController < ApplicationController
  include Wicked::Wizard

  steps :guest, :address, :additional_guest, :summary

  def show

    case step
    when :guest
      @guest = Guest.new
    when :address
      @address = Address.new
    when :additional_guest
      @guest = Guest.new
    when :summary
    end

    render_wizard
  end

  def create_guest
    @guest = Guest.new(guest_params)
    if @guest.save
      session[:guest_id] = @guest.id
      redirect_to wizard_path(:address)
    else
      render 'add_guests/guest'
    end
  end

  def create_additional_guest
    if go_to_summary?(params[:commit])
      redirect_to create_redirect_for(params[:commit])
    else
      guest = Guest.new(guest_params)
      if current_user.guests << guest
        redirect_to create_redirect_for(params[:commit])
      else
        render 'add_guests/guest'
      end
    end
  end

  def create_address
    @address = Address.new(address_params)
    if @address.save
      @guest = Guest.find(session[:guest_id]).update_attribute(:address_id, @address.id)
      redirect_to wizard_path(:additional_guest)
    else
      render 'add_guests/address'
    end
  end

  def finish_wizard_path
    guests_path
  end

  private
  def guest_params
    params.require(:guest).permit(:address_id, :guest_id, :first_name, :last_name, :title, :email, :twenty_one, :eighteen, :user_id)
  end

  def address_params
    params.require(:address).permit(:street_address, :city, :state, :zip_code)
  end

  def go_to_summary?(message)
    params[:commit] == "Go to Summary"
  end

  def one_and_done?(message)
    message == "Add this one then go to Summary"
  end

  def add_more?(message)
    message == "Add More"
  end

  def create_redirect_for(message)
   return wizard_path(:additional_guest) if add_more?(message)
   return wizard_path(:summary)          if one_and_done?(message)
   return wizard_path(:summary)          if go_to_summary?(message)
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render action: 'show', status: :created, location: @address }
      else
        format.html { render action: 'new' }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:street_address, :city, :state, :zip_code)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index

  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_guest, only: [:show, :edit, :update, :destroy]

  # GET /guests
  # GET /guests.json
  def index
    @guests = current_user.guests
  end

  # GET /guests/1
  # GET /guests/1.json
  def show
  end

  # GET /guests/new
  def new
    @guest = Guest.new
  end

  # GET /guests/1/edit
  def edit
  end

  # POST /guests
  # POST /guests.json
  def create
    @guest = Guest.new(guest_params)

    respond_to do |format|
      if @guest.save
        format.html { redirect_to @guest, notice: 'Guest was successfully created.' }
        format.json { render action: 'show', status: :created, location: @guest }
      else
        format.html { render action: 'new' }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guests/1
  # PATCH/PUT /guests/1.json
  def update
    respond_to do |format|
      if @guest.update(guest_params)
        format.html { redirect_to @guest, notice: 'Guest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guests/1
  # DELETE /guests/1.json
  def destroy
    @guest.destroy
    respond_to do |format|
      format.html { redirect_to guests_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guest
      @guest = Guest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guest_params
      params.require(:guest).permit(:address_id, :guest_id, :first_name, :last_name, :title, :email, :twenty_one, :eighteen, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
  def row_styles(guests)
    @row_styles ||= Guests.new(guests).table_row_styles
  end

  def row_style_for(id, guests)
    row_styles(guests)[id]
  end
end

app/views/add_guests/additional_guest.html.haml
%h1 Additional Guests

= form_for @guest, url: "/add_guests/additional_guest", :method => :post  do |f|
  - if @guest.errors.any?
    #error_explanation
      %h2= "#{pluralize(@guest.errors.count, "error")} prohibited this guest from being saved:"
      %ul
        - @guest.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = select_tag(:title, options_for_select(FormalTitle.titles))
  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :twenty_one
    = f.check_box :twenty_one
  .field
    = f.hidden_field :guest_id, { value: session[:guest_id] }
  .actions
    = f.submit 'Add More', class: "btn btn-primary"
    = f.submit 'Add this one then go to Summary', class: "btn btn-primary"
    = f.submit 'Go to Summary', class: "btn btn-primary"

app/views/add_guests/address.html.haml
%h1 Adress
= form_for @address, url: "/add_guests/address", :method => :post do |f|
  - if @address.errors.any?
    #error_explanation
      %h2= "#{pluralize(@address.errors.count, "error")} prohibited this address from being saved:"
      %ul
        - @address.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :street_address
    = f.text_field :street_address
  .field
    = f.label :city
    = f.text_field :city
  .field
    = f.label :state
    = f.text_field :state
  .field
    = f.label :zip_code
    = f.text_field :zip_code
  .field
    = f.hidden_field :guest_id, { value: params[:guest_id] }
  .actions
    = f.submit 'Continue', class: "btn btn-primary"

app/views/add_guests/guest.html.haml
%h1 Guest
= form_for @guest, url: "/add_guests/guest", :method => :post  do |f|
  - if @guest.errors.any?
    #error_explanation
      %h2= "#{pluralize(@guest.errors.count, "error")} prohibited this guest from being saved:"
      %ul
        - @guest.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = select_tag(:title, options_for_select(FormalTitle.titles))
  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :twenty_one
    = f.check_box :twenty_one
  .actions
    = f.submit 'Continue', class: "btn btn-primary"

app/views/add_guests/summary.html.haml
%h1 Summary
= link_to 'skip', next_wizard_path

app/views/addresses/_form.html.haml
= form_for @address do |f|
  - if @address.errors.any?
    #error_explanation
      %h2= "#{pluralize(@address.errors.count, "error")} prohibited this address from being saved:"
      %ul
        - @address.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :street_address
    = f.text_field :street_address
  .field
    = f.label :city
    = f.text_field :city
  .field
    = f.label :state
    = f.text_field :state
  .field
    = f.label :zip_code
    = f.text_field :zip_code
  .actions
    = f.submit 'Save'

app/views/addresses/edit.html.haml
%h1 Editing address

= render 'form'

= link_to 'Show', @address
\|
= link_to 'Back', addresses_path

app/views/addresses/index.html.haml
%h1 Listing addresses

%table
  %tr
    %th Street address
    %th City
    %th State
    %th Zip code
    %th
    %th
    %th

  - @addresses.each do |address|
    %tr
      %td= address.street_address
      %td= address.city
      %td= address.state
      %td= address.zip_code
      %td= link_to 'Show', address
      %td= link_to 'Edit', edit_address_path(address)
      %td= link_to 'Destroy', address, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Address', new_address_path

app/views/addresses/new.html.haml
%h1 New address

= render 'form'

= link_to 'Back', addresses_path

app/views/addresses/show.html.haml
%p#notice= notice

%p
  %b Street address:
  = @address.street_address
%p
  %b City:
  = @address.city
%p
  %b State:
  = @address.state
%p
  %b Zip code:
  = @address.zip_code

= link_to 'Edit', edit_address_path(@address)
\|
= link_to 'Back', addresses_path

app/views/dashboard/index.html.haml
.hero-unit
  %h1 Welcome!
  %p
    Dan's the man is meant to help Dan and Amy out with their wedding Guest List and maybe more, we'll see.
    - if user_signed_in?
      =button_to "Add Guests!", guests_path, method: :get, class: "btn btn-primary"
    - else
      %row
        .span2=button_to "Sign Up Now!", "/users/sign_up", method: :get, class: "btn btn-primary"
        .span1 or
        .span5=button_to "Sign In", "users/sign_in", method: :get, class: "btn btn-primary"

  %h3 Current Features
  %ul
    %li Add Guests by groups, like families or guests with significant others

  %h3 Whats Next
  %ul
    %li View and only to a specific users guest list, right now you can see everyone!

app/views/guests/_form.html.haml
= form_for @guest do |f|
  - if @guest.errors.any?
    #error_explanation
      %h2= "#{pluralize(@guest.errors.count, "error")} prohibited this guest from being saved:"
      %ul
        - @guest.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :address_id
    = f.number_field :address_id
  .field
    = f.label :guest_id
    = f.number_field :guest_id
  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :twenty_one
    = f.check_box :twenty_one
  .field
    = f.label :eighteen
    = f.check_box :eighteen
  .actions
    = f.submit 'Save'

app/views/guests/edit.html.haml
%h1 Editing guest

= render 'form'

= link_to 'Show', @guest
\|
= link_to 'Back', guests_path

app/views/guests/index.html.haml
%row
  .span8
    %h2 Guest List
  .span1
    = button_to "Add more Guests!", add_guests_path, method: :get, class: "btn btn-primary"

%table.table.table-condensed
  %tr
    %th First name
    %th Last name
    %th Title
    %th Email
    %th Older thank 21?
    %th
    %th
    %th

  - @guests.each do |guest|
    %tr{ class: "#{row_style_for(guest.id, @guests) }" }
      %td= guest.first_name
      %td= guest.last_name
      %td= guest.title
      %td= guest.email
      %td= guest.twenty_one
      %td= link_to 'Show', guest
      %td= link_to 'Edit', edit_guest_path(guest)
      %td= link_to 'Destroy', guest, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

app/views/guests/new.html.haml
%h1 New guest

= render 'form'

= link_to 'Back', guests_path

app/views/guests/show.html.haml
%p#notice= notice

%p
  %b Address:
  = @guest.address_id
%p
  %b Guest:
  = @guest.guest_id
%p
  %b First name:
  = @guest.first_name
%p
  %b Last name:
  = @guest.last_name
%p
  %b Title:
  = @guest.title
%p
  %b Email:
  = @guest.email
%p
  %b Twenty one:
  = @guest.twenty_one
%p
  %b Eighteen:
  = @guest.eighteen

= link_to 'Edit', edit_guest_path(@guest)
\|
= link_to 'Back', guests_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title DansTheMan
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .navbar
      .navbar-inner
        =link_to "DansTheMan", dashboard_path, {class: "brand"}
        %ul{class: "nav"}
          %li
            =link_to "Guests", guests_path
          %li
            =link_to "Invitations", "#"
          %li
            =link_to "Cool Stuff I don't know about", "#"
          %li
            =link_to "Logout", "users/sign_out", method: :get
    %container
      %row
        .span11
          .notice=notice
          .alert=alert
          = yield